### ISSUE TITLE
mill.scalalib.GenIdea/idea fails with netty-transport-native-epoll as dependency

### ISSUE THREAD

**Issue by kxa14** [lsug/lsug-website#130]
`mill.scalalib.GenIdea/idea` fails with the following error when executing on a project that has netty-transport-native-epoll as a dependency. 

```
1 targets failed
mill.scalalib.GenIdea.idea java.nio.file.NoSuchFileException: ~/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.46.Final/netty-transport-native-epoll-4.1.46.Final-linux-x86_64.pom
```

It's complaining about a missing pom file which has a `linux-x86_64` suffix. Looking into the `~/.cache/coursier.../4.1.46.Final` directory, we can see the said pom file does not exists, whereas a pom file without the suffix exists. 

```
 ~/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.46.Final:
   netty-transport-native-epoll-4.1.46.Final-linux-x86_64.jar
   netty-transport-native-epoll-4.1.46.Final-sources.jar
   netty-transport-native-epoll-4.1.46.Final.pom 
```

The issue seems to come from the logic in [GenIdeaImpl](https://github.com/com-lihaoyi/mill/blob/6cf96e4b01acd78ff31eed800b4e224d7a425998/scalalib/src/GenIdeaImpl.scala#L333) looks for a POM extension with the same filename as the jar which does not cater for classifiers. 

We think one solution to resolve this issue is to change the code to look for any file with a POM extension in the same directory as the jar.

More detailed information by @zainab-ali can be found here https://github.com/lsug/lsug-website/issues/90

Would you like us to PR this change? Also, thank you for working on and maintaining this build tool. Our project has benefited a lot from this project.

**Comment by zainab-ali** [comment]
Thanks @kxa14! I've a few suggestions:
 - Add the contents of the `~/.cache/coursier.../4.1.46.Final` directory:

   > It's complaining about a missing pom file which has a `linux-x86_64` suffix. Looking into the `~/.cache/coursier.../4.1.46.Final` directory, we can see the said pom file does not exist, whereas a pom file without the suffix exists:
      
   ```
    ~/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.46.Final:
      netty-transport-native-epoll-4.1.46.Final-linux-x86_64.jar
      netty-transport-native-epoll-4.1.46.Final-sources.jar
      netty-transport-native-epoll-4.1.46.Final.pom 
   ```

   The maintainers will have a better idea of what is wrong.

 - GenIdeaImpl should be surrounded by backticks (\`) to give `GenIdeaImpl`. This is a bit easier to read.

 - Add a link to the line in `GenIdeaImpl.scala` in the GitHub repository. You can find this by:

   - Navigating to https://github.com/com-lihaoyi/mill
   - Clicking `Go to file`
   - Searching for `GenIdeaImpl`
   - Clicking on line 333 of the file
   - Clicking `...`
   - Clicking `Copy permalink`

   This should give you https://github.com/com-lihaoyi/mill/blob/6cf96e4b01acd78ff31eed800b4e224d7a425998/scalalib/src/GenIdeaImpl.scala#L333.
  
 - Ask:

   > Would you like us to PR this code change?
   
   We’d be happy to make the fix ourselves, if we were sure they agree with the approach.

 - Thank the maintainers for their excellent project. :slightly_smiling_face: 
   It's hard work maintaining a high quality build tool, and the mill maintainers have done some really amazing stuff.

**Comment by zainab-ali** [comment]
One other thing - you can mention me too.
> More detailed information by @zainab-ali can be found here #90

That means I'll automatically get notified by GitHub when you open the issue.

If you like, you can edit this issue description with the suggestions (click the `...` next to the issue description, and select `edit`) and I can take another look.

**Comment by kxa14** [comment]
Thanks for the suggestions :smiley: I've edited the issue description. Please let me know if further changes are required.

**Comment by zainab-ali** [comment]
@kxa14 it looks great! Go ahead and open it in [mill](https://github.com/com-lihaoyi/mill/issues).

**Comment by kxa14** [comment]
Done it :smiley: We can close this issue now. Thanks for your help :smile:
