### ISSUE TITLE
Add law tests to the parser

### ISSUE THREAD

**Issue by zainab-ali** [lsug/lsug-website#25]
The lsug markup uses an applicative parser.  It has cats type class instances for functor and alternative.
While the parser is unit tested, the instances themselves could use law tests.

## Potential Solution
As we use munit for unit testing, we can add laws with `discipline-munit`. This is described in the [cats laws documentation](https://typelevel.org/cats/typeclasses/lawtesting.html).
The tests should be added in the `lsug.markup.ParserSpec`. Provided there are no test failures, the parser shouldn't be changed.
## Prerequisites
You should be familiar with the some type classes, such as Functor.  You should also understand the concept of unit testing.
## What you'll learn
 - the [alternative type class](https://typelevel.org/cats/typeclasses/alternative.html)
 - how to use [munit](https://scalameta.org/munit/)
 - the basics of property testing
 - what is meant by a type class law, and how to test it with the [discipline](https://github.com/typelevel/discipline) library.
## Getting started
Read our [Contributor Guide](https://github.com/lsug/lsug-website/blob/master/CONTRIBUTING.md) to get set up.

**Comment by kxa14** [comment]
I'm working on this.

**Comment by zainab-ali** [comment]
Thanks for working on this @kxa14 !
