### ISSUE TITLE
Use cert covering multiple domains for SSL

### ISSUE THREAD

**Issue by yilinwei** [lsug/lsug-website#43]
Currently, we're only covering www.lsug.co.uk, but there's a redirect setup for www.lsug.org as well. [Certbot](https://certbot.eff.org/docs/using.html?highlight=domain) supports this option.

**Comment by zainab-ali** [comment]
This has been addressed with the automated certificate renewal: [61052c4ff870e73818e2d43369cbc050b0342551](https://github.com/lsug/lsug-website/tree/61052c4ff870e73818e2d43369cbc050b0342551)
